language: cpp
sudo: required
compiler:
- clang
- gcc
os:
- linux
before_install:
- sudo apt-get update 
- sudo apt-get install build-essential gfortran pkg-config liblapack-dev libblas-dev
- wget --tries=40 --retry-connrefused --waitretry=1 --no-check-certificate https://www.coin-or.org/download/source/Ipopt/Ipopt-3.12.12.tgz
- tar xvzf Ipopt-3.12.12.tgz
- cd Ipopt-3.12.12/
- cd ThirdParty/Mumps
- ./get.Mumps
- cd ../..
- ./configure -disable-static --prefix=/usr/local
- make -j5
- sudo make install
- cd ../
- echo $LANG
- echo $LC_ALL
- mkdir build && cd build && cmake .. -DIpopt=ON
script:
- make -j5
- ../bin/Release/gravity_test
- ../bin/Release/acopf
