language: cpp
sudo: required
compiler:
- gcc
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
before_install:
- export CC=/usr/bin/gcc-6
- export CXX=/usr/bin/g++-6
- sudo apt-get clean
- sudo apt-get update 
- sudo apt-get install build-essential gfortran pkg-config liblapack-dev libblas-dev
- wget --tries=40 --retry-connrefused --waitretry=1 --no-check-certificate https://www.coin-or.org/download/source/Ipopt/Ipopt-3.12.12.tgz
- tar xvzf Ipopt-3.12.12.tgz
- cd Ipopt-3.12.12/
- cd ThirdParty/Mumps
- ./get.Mumps
- cd ../..
- ./configure -disable-static --prefix=/usr/local
- make -j5
- sudo make install
- cd ../
- echo $LANG
- echo $LC_ALL
- mkdir build && cd build && cmake .. -DIpopt=ON
script:
- make -j5
- ../bin/Release/gravity_test
- ../bin/Release/acopf
- ../bin/Release/dcopf
- ../bin/Release/socopf
- ../bin/Release/sdpcuts
- ../bin/Release/svm -nb -1 -mu 1e2
- ../bin/Release/ising
- cd ../
- ./get_code_cov.sh
after_success: 
- bash <(curl -s https://codecov.io/bash) -t 7a0a32a0-cc52-4460-9ec6-c4950095b532
