language: cpp
sudo: required
compiler:
- clang
- gcc
os:
- linux
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install liblapack-dev && sudo apt-get install libblas-dev; fi
- echo $LANG
- echo $LC_ALL
- mkdir build && cd build && cmake ..
script:
- make
- ../bin/Release/gravity_test
