language: cpp
sudo: required
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt update
- sudo apt-get install gcc-6 g++-6
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 60
- sudo apt-get install build-essential gfortran pkg-config liblapack-dev libblas-dev
# To point to the new install
- git clone https://github.com/LAStools/LAStools.git 
- cd LAStools
- make
- export LASlib_ROOT_DIR="/home/travis/build/coin-or/Gravity/LAStools/LASlib"
- cd ..
- wget --tries=40 --retry-connrefused --waitretry=1 --no-check-certificate https://www.coin-or.org/download/source/Ipopt/Ipopt-3.12.12.tgz
- tar xvzf Ipopt-3.12.12.tgz
- mkdir third_party
- mv Ipopt-3.12.12 ./third_party/CoinIpopt
- cd ./third_party/CoinIpopt
- cd ThirdParty/Mumps
- "./get.Mumps"
- cd ../..
- mkdir build
- cd build
- "../configure"
- make -j5
- sudo make install
- ls include/coin
- ls lib
- cd ../../../
- echo $LANG
- echo $LC_ALL
- mkdir build && cd build && cmake .. -DIpopt=ON -DCov=ON -DDebug=ON
script:
- make
- ../bin/Debug/gravity_test
- ../bin/Debug/lidar Reg ../data_sets/LiDAR/toy_model.txt ../data_sets/LiDAR/toy_data.txt GoICP
- cd ../
- ./get_code_cov.sh
after_success: 
- bash <(curl -s https://codecov.io/bash) -t 7a0a32a0-cc52-4460-9ec6-c4950095b532
